pipeline {
    agent any

    tools {
        maven 'Maven 3'  // Ensure 'Maven 3' is configured in Jenkins Global Tool Configuration
        jdk 'Java 11'    // Ensure Java 11 is installed in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub repository (specify 'master' branch)
                git branch: 'master', url: 'https://github.com/KiranTalwar/SeleniumPractice_SwagLabs'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install dependencies using Maven
                sh 'mvn clean install'
            }
        }

        stage('Run Tests') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }
    }

    post {
        always {
            // Archive test results (Make sure the reports are generated by Maven)
            junit '**/target/surefire-reports/*.xml'
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }
    }
}
