pipeline {
    agent any
    tools {
        maven 'Maven 3'  // Make sure 'Maven 3' is configured in Jenkins Global Tool Configuration
        jdk 'Java 11'    // Make sure JDK is installed and configured in Jenkins
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout your project from GitHub repository
                git 'https://github.com/KiranTalwar/SeleniumPractice_SwagLabs'
            }
        }
        stage('Install Dependencies') {
            steps {
                // Install dependencies using Maven
                sh 'mvn clean install'
            }
        }
        stage('Run Tests') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }
    }
    post {
        always {
            // Archive test results (Make sure the reports are generated by Maven)
            junit '**/target/surefire-reports/*.xml'
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }
    }
}
