pipeline {
    agent any

    tools {
        maven 'Maven 3'  // Ensure this is configured in Jenkins Global Tool Configuration
        jdk 'Java 11'    // Ensure this is configured in Jenkins Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your project from GitHub repository
                git credentialsId: 'your-credentials-id', url: 'https://github.com/KiranTalwar/SeleniumPractice_SwagLabs'
                // Use your GitHub credentials if private repository
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install dependencies using Maven
                sh 'mvn clean install'
                // Ensure your pom.xml is correctly configured
            }
        }

        stage('Run Tests') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
                // Ensure your tests are properly configured in your project
            }
        }
    }

    post {
        always {
            // Archive test results (Make sure the reports are generated by Maven)
            junit '**/target/surefire-reports/*.xml'  // Ensure test reports are being generated
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            // Archive build artifacts like jar files if needed
        }
    }
}
